### PR TITLE
implemented updateBallCount in BallPath

### LINKED ISSUE #18: Implement updateBallCount - Mike
See BVA in the branch attached to this issue and only develop in that branch. Once all your tests pass, checkstyle passes, and you're happy with your code, create a pr in GitHub.

To run the tests, you can use the java test runner or the Wpi command Test Robot Code

To run checkstyle, go to the gradle tab (elephant icon on the left side ribbon), and run check (in tasks->verification)

Please message me if you get stuck on something

### PR DESCRIPTION
**Pull request by Bryantm1201**
We should probably have some kind of template or something describing what we want the kids to type here

### CODE REVIEW

**Comment by rhit-edgingza** [comment]
> We should probably have some kind of template or something describing what we want the kids to type here

Agreed, I think we can flesh that out for the fall dry run

**Comment by rhit-edgingza** [comment]
@Bryantm1201 Can you answer a couple questions for me so I can gauge how this went?

-  Approx how long did it take you to finish implementation? How difficult was it?
- Was there anything that you got hung up on?
- Do you think a student (with some more detailed instructions provided in the issue / more practice) could handle implementing code using this flow?
- Any other comments?

**Comment by Bryantm1201** [comment]
It took me maybe 20 minutes to finish, but I'm working on a new system and ran into git setup issues along the way, so probably closer to 10-15 minutes total 

Nothing logically I got caught up on, but I've also done similar systems several times in the past 

First couple of times they may need the help of a mentor to understand the workflow, but it was relatively simple after the fact

line length in checkstyle should be a warning instead of a error. Long descriptions for exceptions or long comments describing what a function does get flagged and cause the checks to fail when complying would make the code worse for someone else to come back and use. Not sure how they handle javadoc comments but javadocs on things like updateBallCount should probably be a thing we look into

**Review by rhit-edgingza — APPROVED** [review]

**Comment by rhit-edgingza** [comment]
Ok. Did you commit your test file code? It doesn't seem to be in the pr I just merged

**Comment by Bryantm1201** [comment]
I didn't edit the test file code at all, did you want me to do that?

**Comment by rhit-edgingza** [comment]
Yes, did you not write any unit tests at all?

**Comment by Bryantm1201** [comment]
lol no oops

**Comment by rhit-edgingza** [comment]
Ah bruh you're supposed to write the tests ;)

**Comment by Bryantm1201** [comment]
shhh they're in there now, 

but we should probably do a better way of listing out things in our BVAs in the future, things like loading at NumOfBalls = 0 and NumOfBalls = 1 resulting in the same effective output (NewNumBalls = NumOfBalls + 1). Also makes implementing tests easier and less repetitive if we are going for a test for each line in the table

**Pull request merged**
